Reduce created / lastUpdated timestamp granularity
InteractiveAdvertisingBureau/iabtcf-java pull request #134
Opened 2022-01-14 08:33 UTC by pmerlet-at-didomi

As described in https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/306 , created and lastUpdated timestamps should have Days granularity only. This PR implements this change in TC String V2 encoder, by removing hours, minutes, seconds and milliseconds information before encoding the date.

Note that decoder is not modified, it will still decode deciseconds granularity for old consent strings.

2022-01-14 18:19 UTC, srinivas81 commented
I am not sure if this fix matches the original design of this java library. In the current implementation, its the decoder that's changing the value to decisecond and leaving the encoder just accept Instant. I am not sure if the java library is designed to create TCF strings in the browser. It's usually for the backend systems.

2022-01-14 18:59 UTC, laktech requested changes
This looks great thanks! My only concern is regarding extending BitWriter with the new business logic.

2022-01-14 18:59 UTC, laktech commented on iabtcf-encoder/src/main/java/com/iabtcf/encoder/TCStringEncoder.java
> +            bitWriter.writeDays(created, CORE_CREATED);
The BitWriter is capable of writing Instants and does not require a "writeDays" method. The class TCStringEncoder is responsible for the "business" logic and should ensure that "created" and "updated" are rounded to the nearest day and pass the resulting Instant to BitWriter#write(Instant).

This rounding method can be made a utility function and can be re-used in your test code which would also eliminate the TestUtils#toDeciDays method.

2022-01-14 19:04 UTC, laktech commented
> I am not sure if this fix matches the original design of this java library. In the current implementation, its the decoder that's changing the value to decisecond and leaving the encoder just accept Instant. I am not sure if the java library is designed to create TCF strings in the browser. It's usually for the backend systems.

This is a good point. The encoder currently accepts any date. We leave it to the system that generates the strings to ensure that the date is properly encoded.

` public Builder created(Instant created)  { ... }`

I'm leaning towards accepting this PR especially because it's how the JS library behaves. Can we add a comment to the builder methods to be clear that  these instants are rounded to the day?

2022-01-17 08:54 UTC, pmerlet-at-didomi commented
Thanks for your feedback, I added comments to the builder. 

I am not familiar with the architecture you chose for the library, of course if you prefer moving the logic into the encoder I am perfectly fine with it. A few advantages I see with having a dedicated method in BitWriter:
- Should be more efficient, as we only manipulate primitive types using simple operations
- No risk of messing up with timezones, we just take UTC time and remove precision below days

2022-02-04 21:29 UTC, srinivas81 commented
@pmerlet-at-didomi According to the [spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-happened-to-created-and-lastupdated) the created and lastUpdated should be the same. Is that something we want to handle in the library, where we change the created timestamp, everytime the updated timestamp is changed?

2022-03-02 18:50 UTC, srinivas81 commented
@pmerlet-at-didomi Do you think you can make the requested changes? If not, I can pick it up. Please let me know. There are few customers who want this patch ASAP.

2022-03-02 23:26 UTC, pmerlet-at-didomi commented
@srinivas81 Sorry, I don't think I will have time to do it this week. If it is needed, of course feel free to make the requested changes in the PR.

2022-04-01 11:09 UTC, closed without merging